spring.application.name=conectaai-gateway
server.port=8080

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml

# configura��es para desenvolvimento local com Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/conectaai
spring.datasource.username=conectaai
spring.datasource.password=conectaai
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Tokens dos gateways (desenvolvimento)
asaas.token=${ASAAS_TOKEN}
stripe.secret=${STRIPE_SECRET}
mp.access.token=${MP_ACCESS_TOKEN}

#JWT
jwt.secret=
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000